-- MySQL Script generated by MySQL Workbench
-- Fri Sep 28 11:04:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hqs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hqs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hqs` DEFAULT CHARACTER SET utf8 ;
USE `hqs` ;

-- -----------------------------------------------------
-- Table `hqs`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hqs`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hqs`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hqs`.`editora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `logo` VARCHAR(20) NULL,
  `site` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hqs`.`quadrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hqs`.`quadrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `data` DATE NULL,
  `capa` VARCHAR(20) NOT NULL,
  `resumo` TEXT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `tipo_id` INT NOT NULL,
  `editora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quadrinho_tipo_idx` (`tipo_id` ASC),
  INDEX `fk_quadrinho_editora1_idx` (`editora_id` ASC),
  CONSTRAINT `fk_quadrinho_tipo`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `hqs`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quadrinho_editora1`
    FOREIGN KEY (`editora_id`)
    REFERENCES `hqs`.`editora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hqs`.`personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hqs`.`personagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nomecivil` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(20) NOT NULL,
  `resumo` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hqs`.`quadrinho_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hqs`.`quadrinho_personagem` (
  `quadrinho_id` INT NOT NULL,
  `personagem_id` INT NOT NULL,
  PRIMARY KEY (`quadrinho_id`, `personagem_id`),
  INDEX `fk_quadrinho_has_personagem_personagem1_idx` (`personagem_id` ASC),
  INDEX `fk_quadrinho_has_personagem_quadrinho1_idx` (`quadrinho_id` ASC),
  CONSTRAINT `fk_quadrinho_has_personagem_quadrinho1`
    FOREIGN KEY (`quadrinho_id`)
    REFERENCES `hqs`.`quadrinho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quadrinho_has_personagem_personagem1`
    FOREIGN KEY (`personagem_id`)
    REFERENCES `hqs`.`personagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
